productions = {
    'S': [['PROGRAMA']],
    'PROGRAMA': [['SECAO_FUNCOES', 'PRINCIPAL']],
    'SECAO_FUNCOES': [['LISTA_FUNCOES'], ['ε']],
    'LISTA_FUNCOES': [['DEC_FUNCAO'], ['LISTA_FUNCOES', 'DEC_FUNCAO']],
    'DEC_FUNCAO': [['TIPO_RETORNO', 'ID', '(', 'PARAMETROS', ')', 'BLOCO']],
    'TIPO_RETORNO': [['TIPO'], ['void']],
    'TIPO': [['TIPO_BASE', 'DIMENSAO']],
    'TIPO_BASE': [['char'], ['float'], ['int'], ['boolean']],
    'DIMENSAO': [['DIMENSAO', '[', 'num_int', ']'], ['ε']],
    'PARAMETROS': [['LISTA_PARAMETROS'], ['ε']],
    'LISTA_PARAMETROS': [['TIPO', 'ID'], ['LISTA_PARAMETROS', ',', 'TIPO', 'ID']],
    'PRINCIPAL': [['main', '(', ')', 'BLOCO']],
    'BLOCO': [['{', 'SECAO_VARIAVEIS', 'SECAO_COMANDOS', '}']],
    'SECAO_VARIAVEIS': [['LISTA_VARIAVEIS'], ['ε']],
    'LISTA_VARIAVEIS': [['TIPO', 'LISTA_ID', ';'], ['LISTA_VARIAVEIS', 'TIPO', 'LISTA_ID', ';']],
    'LISTA_ID': [['ID'], ['LISTA_ID', ',', 'ID']],
    'SECAO_COMANDOS': [['LISTA_COMANDOS'], ['ε']],
    'LISTA_COMANDOS': [['COMANDO'], ['LISTA_COMANDOS', 'COMANDO']],
    'COMANDO': [['LEITURA'], ['ESCRITA'], ['ATRIBUICAO'], ['FUNCAO'], ['SELECAO'], ['ENQUANTO'], ['RETORNO']],
    'LEITURA': [['scanf', '(', 'LISTA_TERMO_LEITURA', ')', ';']],
    'LISTA_TERMO_LEITURA': [['TERMO_LEITURA'], ['LISTA_TERMO_LEITURA', ',', 'TERMO_LEITURA']],
    'TERMO_LEITURA': [['ID', 'DIMENSAO2']],
    'DIMENSAO2': [['DIMENSAO2', '[', 'EXPR_ADITIVA', ']', 'ε']],
    'ESCRITA': [['println', '(', 'LISTA_TERMO_ESCRITA', ')', ';']],
    'LISTA_TERMO_ESCRITA': [['TERMO_ESCRITA'], ['LISTA_TERMO_ESCRITA', ',', 'TERMO_ESCRITA']],
    'TERMO_ESCRITA': [['ID', 'DIMENSAO2'], ['CONSTANTE'], ['texto']],
    'SELECAO': [['if', '(', 'EXPRESSAO', ')', 'BLOCO', 'SENAO']],
    'SENAO': [['else', 'BLOCO'], ['ε']],
    'ENQUANTO': [['while', '(', 'EXPRESSAO', ')', 'BLOCO']],
    'ATRIBUICAO': [['ID', '=', 'COMPLEMENTO', ';']],
    'COMPLEMENTO': [['EXPRESSAO'], ['FUNCAO']],
    'FUNCAO': [['func', 'ID', '(', 'ARGUMENTOS', ')']],
    'ARGUMENTOS': [['LISTA_ARGUMENTOS'], ['ε']],
    'LISTA_ARGUMENTOS': [['EXPRESSAO'], ['LISTA_ARGUMENTOS', ',', 'EXPRESSAO']],
    'RETORNO': [['return', 'EXPRESSAO', ';']],
    'EXPRESSAO': [['EXPR_OU']],
    'EXPR_OU': [['EXPR_E'], ['EXPR_OU', '||', 'EXPR_E']],
    'EXPR_E': [['EXPR_RELACIONAL'], ['EXPR_E', '&&', 'EXPR_RELACIONAL']],
    'EXPR_RELACIONAL': [['EXPR_ADITIVA'], ['EXPR_ADITIVA', 'opRelacional', 'EXPR_ADITIVA']],
    'EXPR_ADITIVA': [['EXPR_MULTIPLICATIVA'], ['EXPR_ADITIVA', 'OP_ADITIVO', 'EXPR_MULTIPLICATIVA']],
    'OP_ADITIVO': [['+'], ['-']],
    'EXPR_MULTIPLICATIVA': [['FATOR'], ['EXPR_MULTIPLICATIVA', 'OP_MULTIPLICATIVO', 'FATOR']],
    'OP_MULTIPLICATIVO': [['*'], ['/'], ['%']],
    'FATOR': [['SINAL', 'ID', 'DIMENSAO2'], ['SINAL', 'CONSTANTE'], ['texto'], ['FATOR'], ['(', 'EXPRESSAO', ')']],
    'SINAL': [['+'], ['-'], ['ε']],
}
