tabela_srl = {
    'Estados': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],

    'Productions': {
        1: {'left': 'Programa', 'right': ['DeclaraçãoLista']},
        2: {'left': 'DeclaraçãoLista', 'right': ['Declaração', 'DeclaraçãoLista']},
        3: {'left': 'DeclaraçãoLista', 'right': []},  # Produção vazia para epsilon
        4: {'left': 'Declaração', 'right': ['DeclaraçãoVariável']},
        5: {'left': 'Declaração', 'right': ['DeclaraçãoFunção']},
        6: {'left': 'DeclaraçãoVariável', 'right': ['Tipo', 'Identificador', ';']},
        7: {'left': 'DeclaraçãoVariável', 'right': ['Tipo', 'Identificador', '[', 'Número', ']', ';']},
        8: {'left': 'DeclaraçãoFunção', 'right': ['Tipo', 'Identificador', '(', 'ListaParâmetros', ')', 'BLOCO']},
        9: {'left': 'Tipo', 'right': ['int']},
        10: {'left': 'Tipo', 'right': ['float']},
        11: {'left': 'Tipo', 'right': ['char']},
        12: {'left': 'Tipo', 'right': ['boolean']},
        13: {'left': 'ListaParâmetros', 'right': ['LISTAVAZIA']},
        14: {'left': 'ListaParâmetros', 'right': ['Tipo', 'Identificador', ',', 'ListaParâmetros']},
        15: {'left': 'BLOCO', 'right': ['{', 'SEÇÃOVARIAVEIS', 'SEÇÃOCOMANDOS', '}']},
        16: {'left': 'SEÇÃOVARIAVEIS', 'right': ['LISTAVARIAVEIS']},
        17: {'left': 'SEÇÃOVARIAVEIS', 'right': ['ε']},
        18: {'left': 'LISTAVARIAVEIS', 'right': ['Tipo', 'LISTAID', ';']},
        19: {'left': 'LISTAVARIAVEIS', 'right': ['LISTAVARIAVEIS', 'Tipo', 'LISTAID', ';']},
        20: {'left': 'LISTAID', 'right': ['identificador']},
        21: {'left': 'LISTAID', 'right': ['LISTAID', ',', 'identificador']},
        22: {'left': 'SEÇÃOCOMANDOS', 'right': ['LISTACOMANDOS']},
        23: {'left': 'SEÇÃOCOMANDOS', 'right': ['ε']},
        24: {'left': 'LISTACOMANDOS', 'right': ['COMANDO']},
        25: {'left': 'LISTACOMANDOS', 'right': ['LISTACOMANDOS', 'COMANDO']},
        26: {'left': 'COMANDO', 'right': ['LEITURA']},
        27: {'left': 'COMANDO', 'right': ['ESCRITA']},
        28: {'left': 'COMANDO', 'right': ['ATRIBUIÇÃO']},
        29: {'left': 'COMANDO', 'right': ['FUNÇÃO']},
        30: {'left': 'COMANDO', 'right': ['SELEÇÃO']},
        31: {'left': 'COMANDO', 'right': ['ENQUANTO']},
        32: {'left': 'COMANDO', 'right': ['RETORNO']},
        33: {'left': 'LEITURA', 'right': ['scanf', '(', 'LISTATERMOLEITURA', ')', ';']},
        34: {'left': 'LISTATERMOLEITURA', 'right': ['TERMOLEITURA']},
        35: {'left': 'LISTATERMOLEITURA', 'right': ['LISTATERMOLEITURA', ',', 'TERMOLEITURA']},
        36: {'left': 'TERMOLEITURA', 'right': ['identificador', 'DIMENSAO2']},
        37: {'left': 'DIMENSAO2', 'right': ['DIMENSAO2', '[', 'EXPR_ADITIVA', ']', 'ε']},
        38: {'left': 'ESCRITA', 'right': ['println', '(', 'LISTATERMOESCRITA', ')', ';']},
        39: {'left': 'LISTATERMOESCRITA', 'right': ['TERMOESCRITA']},
        40: {'left': 'LISTATERMOESCRITA', 'right': ['LISTATERMOESCRITA', ',', 'TERMOESCRITA']},
        41: {'left': 'TERMOESCRITA', 'right': ['identificador', 'DIMENSAO2']},
        42: {'left': 'TERMOESCRITA', 'right': ['CONSTANTE']},
        43: {'left': 'TERMOESCRITA', 'right': ['texto']},
        44: {'left': 'SELEÇÃO', 'right': ['if', '(', 'EXPRESSÃO', ')', 'BLOCO', 'SENÃO']},
        45: {'left': 'SENÃO', 'right': ['else', 'BLOCO', 'ε']},
        46: {'left': 'ENQUANTO', 'right': ['while', '(', 'EXPRESSÃO', ')', 'BLOCO']},
        47: {'left': 'ATRIBUIÇÃO', 'right': ['identificador', '=', 'COMPLEMENTO', ';']},
        48: {'left': 'COMPLEMENTO', 'right': ['EXPRESSÃO']},
        49: {'left': 'COMPLEMENTO', 'right': ['FUNÇÃO']},
        50: {'left': 'FUNÇÃO', 'right': ['func', 'identificador', '(', 'ARGUMENTOS', ')']},
        51: {'left': 'ARGUMENTOS', 'right': ['LISTAARGUMENTOS']},
        52: {'left': 'ARGUMENTOS', 'right': ['ε']},
        53: {'left': 'LISTAARGUMENTOS', 'right': ['EXPRESSÃO']},
        54: {'left': 'LISTAARGUMENTOS', 'right': ['LISTAARGUMENTOS', ',', 'EXPRESSÃO']},
        55: {'left': 'RETORNO', 'right': ['return', 'EXPRESSÃO', ';']},
        56: {'left': 'EXPRESSÃO', 'right': ['EXPR_OU']},
        57: {'left': 'EXPR_OU', 'right': ['EXPR_E']},
        58: {'left': 'EXPR_OU', 'right': ['EXPR_OU', '||', 'EXPR_E']},
        59: {'left': 'EXPR_E', 'right': ['EXPR_RELACIONAL']},
        60: {'left': 'EXPR_E', 'right': ['EXPR_E', '&&', 'EXPR_RELACIONAL']},
        61: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA']},
        62: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA', 'opRelacional', 'EXPR_ADITIVA']},
        63: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_MULTIPLICATIVA']},
        64: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_ADITIVA', 'OP_ADITIVO', 'EXPR_MULTIPLICATIVA']},
        65: {'left': 'OP_ADITIVO', 'right': ['+']},
        66: {'left': 'OP_ADITIVO', 'right': ['-']},
        67: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['FATOR']},
        68: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['EXPR_MULTIPLICATIVA', 'OP_MULTIPLICATIVO', 'FATOR']},
        69: {'left': 'OP_MULTIPLICATIVO', 'right': ['*']},
        70: {'left': 'OP_MULTIPLICATIVO', 'right': ['/']},
        71: {'left': 'OP_MULTIPLICATIVO', 'right': ['%']},
        72: {'left': 'FATOR', 'right': ['SINAL', 'identificador', 'DIMENSAO2']},
        73: {'left': 'FATOR', 'right': ['SINAL', 'CONSTANTE']},
        74: {'left': 'FATOR', 'right': ['texto']},
        75: {'left': 'FATOR', 'right': ['!', 'FATOR']},
        76: {'left': 'FATOR', 'right': ['(', 'EXPRESSÃO', ')']},
        77: {'left': 'SINAL', 'right': ['+']},
        78: {'left': 'SINAL', 'right': ['-']},
        79: {'left': 'SINAL', 'right': ['ε']},
        80: {'left': 'CONSTANTE', 'right': ['num_int']},
        81: {'left': 'CONSTANTE', 'right': ['num_dec']},
    },

    'Ação': {
        0: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6'},
        1: {'$': 'acc'},
        2: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '$': 'R3'},
        3: {'identificador': 'S7'},
        4: {'identificador': 'S8'},
        5: {'identificador': 'S9'},
        6: {'identificador': 'S10'},
        7: {';': 'R6'},
        8: {'(': 'S11'},
        9: {'(': 'S12'},
        10: {'(': 'S13'},
        11: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        12: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        13: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        14: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        15: {'}': 'R15'},
        16: {'}': 'R16'},
        17: {'}': 'R17'},
        18: {'}': 'R18'},
        19: {'}': 'R19'},
        20: {'}': 'R20'},
        21: {'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        22: {'{': 'S15', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        23: {'{': 'S16', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        24: {'{': 'S17', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        25: {'{': 'S18', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        26: {'{': 'S19', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        27: {'}': 'R15'},
        28: {'}': 'R16'},
        29: {'}': 'R17'},
        30: {'}': 'R18'},
        31: {'}': 'R19'},
        32: {'}': 'R20'},
        33: {'identificador': 'S7'},
        34: {'identificador': 'S7'},
        35: {'identificador': 'S7'},
        36: {'identificador': 'S7'},
        37: {'identificador': 'S7'},
        38: {'identificador': 'S7'},
        39: {'identificador': 'S7'},
        40: {'identificador': 'S7'},
        41: {'identificador': 'S7'},
        42: {'identificador': 'S7'},
        43: {'identificador': 'S7'},
        44: {'identificador': 'S7'},
        45: {'identificador': 'S7'},
        46: {'identificador': 'S7'},
        47: {'identificador': 'S7'},
        48: {'identificador': 'S7'},
        49: {'identificador': 'S7'},
        50: {'identificador': 'S7'},
        51: {'identificador': 'S7'},
        52: {'identificador': 'S7'},
        53: {'identificador': 'S7'},
        54: {'identificador': 'S7'},
        55: {'identificador': 'S7'},
        56: {'identificador': 'S7'},
        57: {'identificador': 'S7'},
        58: {'identificador': 'S7'},
        59: {'identificador': 'S7'},
        60: {'identificador': 'S7'},
        61: {'identificador': 'S7'},
        62: {'identificador': 'S7'},
        63: {'identificador': 'S7'},
        64: {'identificador': 'S7'},
        65: {'identificador': 'S7'},
        66: {'identificador': 'S7'},
        67: {'identificador': 'S7'},
        68: {'identificador': 'S7'},
        69: {'identificador': 'S7'},
        70: {'identificador': 'S7'},
        71: {'identificador': 'S7'},
        72: {'identificador': 'S7'},
        73: {'identificador': 'S7'},
        74: {'identificador': 'S7'},
        75: {'identificador': 'S7'},
        76: {'identificador': 'S7'},
        77: {'identificador': 'S7'},
        78: {'identificador': 'S7'},
        79: {'identificador': 'S7'},
        80: {'identificador': 'S7'},
        81: {'identificador': 'S7'},
    },

    'Goto': {
        0: {'DeclaraçãoLista': 1},
        1: {'DeclaraçãoLista': 2, 'Declaração': 3, 'ε': 4},
        5: {'Declaração': 5},
        8: {'Tipo': 9},
        9: {'LISTAID': 10},
        15: {'SEÇÃOVARIAVEIS': 16, 'ε': 17},
        16: {'LISTAVARIAVEIS': 18},
        18: {'Tipo': 19},
        19: {'LISTAID': 21},
        21: {';': 22},
        24: {'SEÇÃOCOMANDOS': 25, 'ε': 23},
        25: {'LISTACOMANDOS': 26},
        26: {'COMANDO': 27},
        27: {'LEITURA': 29, 'ESCRITA': 30, 'ATRIBUIÇÃO': 31, 'FUNÇÃO': 32, 'SELEÇÃO': 33, 'ENQUANTO': 34, 'RETORNO': 35},
        33: {'if': 36},
        36: {'(': 37},
        37: {'EXPRESSÃO': 38},
        38: {')': 39},
        39: {'BLOCO': 40},
        40: {'SENÃO': 41},
        41: {'{': 42},
        42: {'BLOCO': 43},
        43: {'}': 44},
        44: {'ε': 45},
        46: {'while': 47},
        47: {'(': 48},
        48: {'EXPRESSÃO': 49},
        49: {')': 50},
        50: {'BLOCO': 51},
        55: {'return': 56},
        56: {'EXPRESSÃO': 57},
        57: {';': 58},
    }
}


tabela_slr = {
    'Estados': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],

    'Productions': {
        1: {'left': 'Programa', 'right': ['DeclaraçãoLista']},
        2: {'left': 'DeclaraçãoLista', 'right': ['Declaração', 'DeclaraçãoLista']},
        3: {'left': 'DeclaraçãoLista', 'right': []},  # Produção vazia para epsilon
        4: {'left': 'Declaração', 'right': ['DeclaraçãoVariável']},
        5: {'left': 'Declaração', 'right': ['DeclaraçãoFunção']},
        6: {'left': 'DeclaraçãoVariável', 'right': ['Tipo', 'Identificador', ';']},
        7: {'left': 'DeclaraçãoVariável', 'right': ['Tipo', 'Identificador', '[', 'Número', ']', ';']},
        8: {'left': 'DeclaraçãoFunção', 'right': ['Tipo', 'Identificador', '(', 'ListaParâmetros', ')', 'BLOCO']},
        9: {'left': 'Tipo', 'right': ['int']},
        10: {'left': 'Tipo', 'right': ['float']},
        11: {'left': 'Tipo', 'right': ['char']},
        12: {'left': 'Tipo', 'right': ['boolean']},
        13: {'left': 'ListaParâmetros', 'right': ['LISTAVAZIA']},
        14: {'left': 'ListaParâmetros', 'right': ['Tipo', 'Identificador', ',', 'ListaParâmetros']},
        15: {'left': 'BLOCO', 'right': ['{', 'SEÇÃOVARIAVEIS', 'SEÇÃOCOMANDOS', '}']},
        16: {'left': 'SEÇÃOVARIAVEIS', 'right': ['LISTAVARIAVEIS']},
        17: {'left': 'SEÇÃOVARIAVEIS', 'right': ['ε']},
        18: {'left': 'LISTAVARIAVEIS', 'right': ['Tipo', 'LISTAID', ';']},
        19: {'left': 'LISTAVARIAVEIS', 'right': ['LISTAVARIAVEIS', 'Tipo', 'LISTAID', ';']},
        20: {'left': 'LISTAID', 'right': ['identificador']},
        21: {'left': 'LISTAID', 'right': ['LISTAID', ',', 'identificador']},
        22: {'left': 'SEÇÃOCOMANDOS', 'right': ['LISTACOMANDOS']},
        23: {'left': 'SEÇÃOCOMANDOS', 'right': ['ε']},
        24: {'left': 'LISTACOMANDOS', 'right': ['COMANDO']},
        25: {'left': 'LISTACOMANDOS', 'right': ['LISTACOMANDOS', 'COMANDO']},
        26: {'left': 'COMANDO', 'right': ['LEITURA']},
        27: {'left': 'COMANDO', 'right': ['ESCRITA']},
        28: {'left': 'COMANDO', 'right': ['ATRIBUIÇÃO']},
        29: {'left': 'COMANDO', 'right': ['FUNÇÃO']},
        30: {'left': 'COMANDO', 'right': ['SELEÇÃO']},
        31: {'left': 'COMANDO', 'right': ['ENQUANTO']},
        32: {'left': 'COMANDO', 'right': ['RETORNO']},
        33: {'left': 'LEITURA', 'right': ['scanf', '(', 'LISTATERMOLEITURA', ')', ';']},
        34: {'left': 'LISTATERMOLEITURA', 'right': ['TERMOLEITURA']},
        35: {'left': 'LISTATERMOLEITURA', 'right': ['LISTATERMOLEITURA', ',', 'TERMOLEITURA']},
        36: {'left': 'TERMOLEITURA', 'right': ['identificador', 'DIMENSAO2']},
        37: {'left': 'DIMENSAO2', 'right': ['DIMENSAO2', '[', 'EXPR_ADITIVA', ']', 'ε']},
        38: {'left': 'ESCRITA', 'right': ['println', '(', 'LISTATERMOESCRITA', ')', ';']},
        39: {'left': 'LISTATERMOESCRITA', 'right': ['TERMOESCRITA']},
        40: {'left': 'LISTATERMOESCRITA', 'right': ['LISTATERMOESCRITA', ',', 'TERMOESCRITA']},
        41: {'left': 'TERMOESCRITA', 'right': ['identificador', 'DIMENSAO2']},
        42: {'left': 'TERMOESCRITA', 'right': ['CONSTANTE']},
        43: {'left': 'TERMOESCRITA', 'right': ['texto']},
        44: {'left': 'SELEÇÃO', 'right': ['if', '(', 'EXPRESSÃO', ')', 'BLOCO', 'SENÃO']},
        45: {'left': 'SENÃO', 'right': ['else', 'BLOCO', 'ε']},
        46: {'left': 'ENQUANTO', 'right': ['while', '(', 'EXPRESSÃO', ')', 'BLOCO']},
        47: {'left': 'ATRIBUIÇÃO', 'right': ['identificador', '=', 'COMPLEMENTO', ';']},
        48: {'left': 'COMPLEMENTO', 'right': ['EXPRESSÃO']},
        49: {'left': 'COMPLEMENTO', 'right': ['FUNÇÃO']},
        50: {'left': 'FUNÇÃO', 'right': ['func', 'identificador', '(', 'ARGUMENTOS', ')']},
        51: {'left': 'ARGUMENTOS', 'right': ['LISTAARGUMENTOS']},
        52: {'left': 'ARGUMENTOS', 'right': ['ε']},
        53: {'left': 'LISTAARGUMENTOS', 'right': ['EXPRESSÃO']},
        54: {'left': 'LISTAARGUMENTOS', 'right': ['LISTAARGUMENTOS', ',', 'EXPRESSÃO']},
        55: {'left': 'RETORNO', 'right': ['return', 'EXPRESSÃO', ';']},
        56: {'left': 'EXPRESSÃO', 'right': ['EXPR_OU']},
        57: {'left': 'EXPR_OU', 'right': ['EXPR_E']},
        58: {'left': 'EXPR_OU', 'right': ['EXPR_OU', '||', 'EXPR_E']},
        59: {'left': 'EXPR_E', 'right': ['EXPR_RELACIONAL']},
        60: {'left': 'EXPR_E', 'right': ['EXPR_E', '&&', 'EXPR_RELACIONAL']},
        61: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA']},
        62: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA', 'opRelacional', 'EXPR_ADITIVA']},
        63: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_MULTIPLICATIVA']},
        64: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_ADITIVA', 'OP_ADITIVO', 'EXPR_MULTIPLICATIVA']},
        65: {'left': 'OP_ADITIVO', 'right': ['+']},
        66: {'left': 'OP_ADITIVO', 'right': ['-']},
        67: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['FATOR']},
        68: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['EXPR_MULTIPLICATIVA', 'OP_MULTIPLICATIVO', 'FATOR']},
        69: {'left': 'OP_MULTIPLICATIVO', 'right': ['*']},
        70: {'left': 'OP_MULTIPLICATIVO', 'right': ['/']},
        71: {'left': 'OP_MULTIPLICATIVO', 'right': ['%']},
        72: {'left': 'FATOR', 'right': ['SINAL', 'identificador', 'DIMENSAO2']},
        73: {'left': 'FATOR', 'right': ['SINAL', 'CONSTANTE']},
        74: {'left': 'FATOR', 'right': ['texto']},
        75: {'left': 'FATOR', 'right': ['!', 'FATOR']},
        76: {'left': 'FATOR', 'right': ['(', 'EXPRESSÃO', ')']},
        77: {'left': 'SINAL', 'right': ['+']},
        78: {'left': 'SINAL', 'right': ['-']},
        79: {'left': 'SINAL', 'right': ['ε']},
        80: {'left': 'CONSTANTE', 'right': ['num_int']},
        81: {'left': 'CONSTANTE', 'right': ['num_dec']},
    },

    'Ação': {
        0: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6'},
        1: {'$': 'acc'},
        2: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '$': 'R3'},
        3: {'identificador': 'S7'},
        4: {'identificador': 'S8'},
        5: {'identificador': 'S9'},
        6: {'identificador': 'S10'},
        7: {';': 'R6'},
        8: {'(': 'S11'},
        9: {'(': 'S12'},
        10: {'(': 'S13'},
        11: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        12: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        13: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        14: {'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', '{': 'S20'},
        15: {'}': 'R15'},
        16: {'}': 'R16'},
        17: {'}': 'R17'},
        18: {'}': 'R18'},
        19: {'}': 'R19'},
        20: {'}': 'R20'},
        21: {'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        22: {'{': 'S15', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        23: {'{': 'S16', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        24: {'{': 'S17', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        25: {'{': 'S18', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        26: {'{': 'S19', 'int': 'S3', 'float': 'S4', 'char': 'S5', 'boolean': 'S6', 'scanf': 'S33', 'println': 'S38', 'if': 'S44', 'while': 'S46', 'return': 'S55', 'identificador': 'S7'},
        27: {'}': 'R15'},
        28: {'}': 'R16'},
        29: {'}': 'R17'},
        30: {'}': 'R18'},
        31: {'}': 'R19'},
        32: {'}': 'R20'},
        33: {'identificador': 'S7'},
        34: {'identificador': 'S7'},
        35: {'identificador': 'S7'},
        36: {'identificador': 'S7'},
        37: {'identificador': 'S7'},
        38: {'identificador': 'S7'},
        39: {'identificador': 'S7'},
        40: {'identificador': 'S7'},
        41: {'identificador': 'S7'},
        42: {'identificador': 'S7'},
        43: {'identificador': 'S7'},
        44: {'identificador': 'S7'},
        45: {'identificador': 'S7'},
        46: {'identificador': 'S7'},
        47: {'identificador': 'S7'},
        48: {'identificador': 'S7'},
        49: {'identificador': 'S7'},
        50: {'identificador': 'S7'},
        51: {'identificador': 'S7'},
        52: {'identificador': 'S7'},
        53: {'identificador': 'S7'},
        54: {'identificador': 'S7'},
        55: {'identificador': 'S7'},
        56: {'identificador': 'S7'},
        57: {'identificador': 'S7'},
        58: {'identificador': 'S7'},
        59: {'identificador': 'S7'},
        60: {'identificador': 'S7'},
        61: {'identificador': 'S7'},
        62: {'identificador': 'S7'},
        63: {'identificador': 'S7'},
        64: {'identificador': 'S7'},
        65: {'identificador': 'S7'},
        66: {'identificador': 'S7'},
        67: {'identificador': 'S7'},
        68: {'identificador': 'S7'},
        69: {'identificador': 'S7'},
        70: {'identificador': 'S7'},
        71: {'identificador': 'S7'},
        72: {'identificador': 'S7'},
        73: {'identificador': 'S7'},
        74: {'identificador': 'S7'},
        75: {'identificador': 'S7'},
        76: {'identificador': 'S7'},
        77: {'identificador': 'S7'},
        78: {'identificador': 'S7'},
        79: {'identificador': 'S7'},
        80: {'identificador': 'S7'},
        81: {'identificador': 'S7'},
    },

    'Goto': {
        0: {'DeclaraçãoLista': 1},
        1: {'DeclaraçãoLista': 2, 'Declaração': 3, 'ε': 4},
        5: {'Declaração': 5},
        8: {'Tipo': 9},
        9: {'LISTAID': 10},
        15: {'SEÇÃOVARIAVEIS': 16, 'ε': 17},
        16: {'LISTAVARIAVEIS': 18},
        18: {'Tipo': 19},
        19: {'LISTAID': 21},
        21: {';': 22},
        24: {'SEÇÃOCOMANDOS': 25, 'ε': 23},
        25: {'LISTACOMANDOS': 26},
        26: {'COMANDO': 27},
        27: {'LEITURA': 29, 'ESCRITA': 30, 'ATRIBUIÇÃO': 31, 'FUNÇÃO': 32, 'SELEÇÃO': 33, 'ENQUANTO': 34, 'RETORNO': 35},
        33: {'if': 36},
        36: {'(': 37},
        37: {'EXPRESSÃO': 38},
        38: {')': 39},
        39: {'BLOCO': 40},
        40: {'SENÃO': 41},
        41: {'{': 42},
        42: {'BLOCO': 43},
        43: {'}': 44},
        44: {'ε': 45},
        46: {'while': 47},
        47: {'(': 48},
        48: {'EXPRESSÃO': 49},
        49: {')': 50},
        50: {'BLOCO': 51},
        55: {'return': 56},
        56: {'EXPRESSÃO': 57},
        57: {';': 58},
    }
}

tabela_slr = {
    'productions ': {
        1: {'left': 'PROGRAMA', 'right': ['SEÇÃOFUNÇÕES', 'PRINCIPAL']},
        2: {'left': 'SEÇÃOFUNÇÕES', 'right': ['LISTAFUNÇÕES']},
        3: {'left': 'SEÇÃOFUNÇÕES', 'right': ['ε']},
        4: {'left': 'LISTAFUNÇÕES', 'right': ['DECFUNÇÃO']},
        5: {'left': 'LISTAFUNÇÕES', 'right': ['LISTAFUNÇÕES', 'DECFUNÇÃO']},
        6: {'left': 'DECFUNÇÃO', 'right': ['TIPORETORNO', 'id', '(', 'PARÂMETROS', ')', 'BLOCO']},
        7: {'left': 'TIPORETORNO', 'right': ['TIPO']},
        8: {'left': 'TIPORETORNO', 'right': ['void']},
        9: {'left': 'TIPO', 'right': ['TIPOBASE', 'DIMENSÃO']},
        10: {'left': 'TIPOBASE', 'right': ['char']},
        11: {'left': 'TIPOBASE', 'right': ['float']},
        12: {'left': 'TIPOBASE', 'right': ['int']},
        13: {'left': 'TIPOBASE', 'right': ['boolean']},
        14: {'left': 'DIMENSÃO', 'right': ['DIMENSÃO', '[', 'num_int', ']']},
        15: {'left': 'DIMENSÃO', 'right': ['ε']},
        16: {'left': 'PARÂMETROS', 'right': ['LISTAPARÂMETROS']},
        17: {'left': 'PARÂMETROS', 'right': ['ε']},
        18: {'left': 'LISTAPARÂMETROS', 'right': ['TIPO', 'id']},
        19: {'left': 'LISTAPARÂMETROS', 'right': ['LISTAPARÂMETROS', ',', 'TIPO', 'id']},
        20: {'left': 'PRINCIPAL', 'right': ['main', '(', ')', 'BLOCO']},
        21: {'left': 'BLOCO', 'right': ['{', 'SEÇÃOVARIAVEIS', 'SEÇÃOCOMANDOS', '}']},
        22: {'left': 'SEÇÃOVARIAVEIS', 'right': ['LISTAVARIAVEIS']},
        23: {'left': 'SEÇÃOVARIAVEIS', 'right': ['ε']},
        24: {'left': 'LISTAVARIAVEIS', 'right': ['TIPO', 'LISTAID', ';']},
        25: {'left': 'LISTAVARIAVEIS', 'right': ['LISTAVARIAVEIS', 'TIPO', 'LISTAID', ';']},
        26: {'left': 'LISTAID', 'right': ['identificador']},
        27: {'left': 'LISTAID', 'right': ['LISTAID', ',', 'identificador']},
        28: {'left': 'SEÇÃOCOMANDOS', 'right': ['LISTACOMANDOS']},
        29: {'left': 'SEÇÃOCOMANDOS', 'right': ['ε']},
        30: {'left': 'LISTACOMANDOS', 'right': ['COMANDO']},
        31: {'left': 'LISTACOMANDOS', 'right': ['LISTACOMANDOS', 'COMANDO']},
        32: {'left': 'COMANDO', 'right': ['LEITURA']},
        33: {'left': 'COMANDO', 'right': ['ESCRITA']},
        34: {'left': 'COMANDO', 'right': ['ATRIBUIÇÃO']},
        35: {'left': 'COMANDO', 'right': ['FUNÇÃO']},
        36: {'left': 'COMANDO', 'right': ['SELEÇÃO']},
        37: {'left': 'COMANDO', 'right': ['ENQUANTO']},
        38: {'left': 'COMANDO', 'right': ['RETORNO']},
        39: {'left': 'LEITURA', 'right': ['scanf', '(', 'LISTATERMOLEITURA', ')', ';']},
        40: {'left': 'LISTATERMOLEITURA', 'right': ['TERMOLEITURA']},
        41: {'left': 'LISTATERMOLEITURA', 'right': ['LISTATERMOLEITURA', ',', 'TERMOLEITURA']},
        42: {'left': 'TERMOLEITURA', 'right': ['id', 'DIMENSAO2']},
        43: {'left': 'DIMENSAO2', 'right': ['DIMENSAO2', '[', 'EXPR_ADITIVA', ']']},
        44: {'left': 'DIMENSAO2', 'right': ['ε']},
        45: {'left': 'ESCRITA', 'right': ['println', '(', 'LISTATERMOESCRITA', ')', ';']},
        46: {'left': 'LISTATERMOESCRITA', 'right': ['TERMOESCRITA']},
        47: {'left': 'LISTATERMOESCRITA', 'right': ['LISTATERMOESCRITA', ',', 'TERMOESCRITA']},
        48: {'left': 'TERMOESCRITA', 'right': ['id', 'DIMENSAO2']},
        49: {'left': 'TERMOESCRITA', 'right': ['CONSTANTE']},
        50: {'left': 'TERMOESCRITA', 'right': ['texto']},
        51: {'left': 'SELEÇÃO', 'right': ['if', '(', 'EXPRESSÃO', ')', 'BLOCO', 'SENÃO']},
        52: {'left': 'SENÃO', 'right': ['else', 'BLOCO']},
        53: {'left': 'SENÃO', 'right': ['ε']},
        54: {'left': 'ENQUANTO', 'right': ['while', '(', 'EXPRESSÃO', ')', 'BLOCO']},
        55: {'left': 'ATRIBUIÇÃO', 'right': ['id', '=', 'COMPLEMENTO', ';']},
        56: {'left': 'COMPLEMENTO', 'right': ['EXPRESSÃO']},
        57: {'left': 'COMPLEMENTO', 'right': ['FUNÇÃO']},
        58: {'left': 'FUNÇÃO', 'right': ['func', 'id', '(', 'ARGUMENTOS', ')']},
        59: {'left': 'ARGUMENTOS', 'right': ['LISTAARGUMENTOS']},
        60: {'left': 'ARGUMENTOS', 'right': ['ε']},
        61: {'left': 'LISTAARGUMENTOS', 'right': ['EXPRESSÃO']},
        62: {'left': 'LISTAARGUMENTOS', 'right': ['LISTAARGUMENTOS', ',', 'EXPRESSÃO']},
        63: {'left': 'RETORNO', 'right': ['return', 'EXPRESSÃO', ';']},
        64: {'left': 'EXPRESSÃO', 'right': ['EXPR_OU']},
        65: {'left': 'EXPR_OU', 'right': ['EXPR_E']},
        66: {'left': 'EXPR_OU', 'right': ['EXPR_OU', '||', 'EXPR_E']},
        67: {'left': 'EXPR_E', 'right': ['EXPR_RELACIONAL']},
        68: {'left': 'EXPR_E', 'right': ['EXPR_E', '&&', 'EXPR_RELACIONAL']},
        69: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA']},
        70: {'left': 'EXPR_RELACIONAL', 'right': ['EXPR_ADITIVA', 'opRelacional', 'EXPR_ADITIVA']},
        71: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_MULTIPLICATIVA']},
        72: {'left': 'EXPR_ADITIVA', 'right': ['EXPR_ADITIVA', 'OP_ADITIVO', 'EXPR_MULTIPLICATIVA']},
        73: {'left': 'OP_ADITIVO', 'right': ['+']},
        74: {'left': 'OP_ADITIVO', 'right': ['-']},
        75: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['FATOR']},
        76: {'left': 'EXPR_MULTIPLICATIVA', 'right': ['EXPR_MULTIPLICATIVA', 'OP_MULTIPLICATIVO', 'FATOR']},
        77: {'left': 'OP_MULTIPLICATIVO', 'right': ['*']},
        78: {'left': 'OP_MULTIPLICATIVO', 'right': ['/']},
        79: {'left': 'OP_MULTIPLICATIVO', 'right': ['%']},
        80: {'left': 'FATOR', 'right': ['SINAL', 'identificador', 'DIMENSAO2']},
        81: {'left': 'FATOR', 'right': ['SINAL', 'CONSTANTE']},
        82: {'left': 'FATOR', 'right': ['texto']},
        83: {'left': 'FATOR', 'right': ['!', 'FATOR']},
        84: {'left': 'FATOR', 'right': ['(', 'EXPRESSÃO', ')']},
        85: {'left': 'CONSTANTE', 'right': ['num_int']},
        86: {'left': 'CONSTANTE', 'right': ['num_dec']},
        87: {'left': 'SINAL', 'right': ['+']},
        88: {'left': 'SINAL', 'right': ['-']},
        89: {'left': 'SINAL', 'right': ['ε']}
    },

    'action_table' : {
        0: {'SEÇÃOFUNÇÕES': 'S1', 'PRINCIPAL': 'S2', 'PROGRAMA': 'G1'},
        1: {'LISTAFUNÇÕES': 'S3', 'ε': 'S4'},
        2: {'main': 'S5'},
        3: {'DECFUNÇÃO': 'S6'},
        4: {'$': 'ACCEPT'},
        5: {'(': 'S7'},
        6: {'TIPORETORNO': 'S8'},
        7: {'LISTAPARÂMETROS': 'S9', 'ε': 'S10'},
        8: {'TIPO': 'S11', 'void': 'S12'},
        9: {'id': 'S13'},
        10: {')': 'R17'},
        11: {'TIPOBASE': 'S14'},
        12: {'(': 'S15'},
        13: {'{': 'S16'},
        14: {'char': 'S17', 'float': 'S18', 'int': 'S19', 'boolean': 'S20'},
        15: {')': 'R60'},
        16: {'SEÇÃOVARIAVEIS': 'S21', 'SEÇÃOCOMANDOS': 'S22'},
        17: {'LISTAVARIAVEIS': 'S23', 'ε': 'S24'},
        18: {'{': 'S25'},
        19: {'main': 'S26'},
        20: {'}': 'R29'},
        21: {'TIPO': 'S27', 'ε': 'S28'},
        22: {'LISTACOMANDOS': 'S29', 'ε': 'S30'},
        23: {'identificador': 'S31'},
        24: {'}': 'R22'},
        25: {'TIPO': 'S32'},
        26: {'identificador': 'S33'},
        27: {'DECFUNÇÃO': 'S34'},
        28: {'ε': 'R31'}
    },

    'goto_table' : {
        0: {'SEÇÃOFUNÇÕES': 1, 'PRINCIPAL': 2, 'PROGRAMA': 1},
        1: {'LISTAFUNÇÕES': 3, 'ε': 4},
        2: {'main': 5},
        3: {'DECFUNÇÃO': 6},
        4: {'$': 'ACCEPT'},
        5: {'(': 7},
        6: {'TIPORETORNO': 8},
        7: {'LISTAPARÂMETROS': 9, 'ε': 10},
        8: {'TIPO': 11, 'void': 12},
        9: {'id': 13},
        10: {')': 'R17'},
        11: {'TIPOBASE': 14},
        12: {'(': 15},
        13: {'{': 16},
        14: {'char': 17, 'float': 18, 'int': 19, 'boolean': 20},
        15: {')': 'R60'},
        16: {'SEÇÃOVARIAVEIS': 21, 'SEÇÃOCOMANDOS': 22},
        17: {'LISTAVARIAVEIS': 23, 'ε': 24},
        18: {'{': 25},
        19: {'main': 26},
        20: {'}': 'R29'},
        21: {'TIPO': 27, 'ε': 28},
        22: {'LISTACOMANDOS': 29, 'ε': 30},
        23: {'identificador': 31},
        24: {'}': 'R22'},
        25: {'TIPO': 32},
        26: {'identificador': 33},
        27: {'DECFUNÇÃO': 34},
        28: {'ε': 'R31'}
    }

}